
#ifndef __CX_CHAT_OPCODES__
#define __CX_CHAT_OPCODES__

enum nOpCodes
{
    CONNECT_CHAT            =  10,
    CONNECTED_CHAT          =  20,
    CONNECTED_HOST          =  21,
    DISCONNECTED_CHAT       =  25,
    QUIT_CHAT               =  30,
    PING_CHAT               =  35,
    PONG_CHAT               =  40,
    CHANGE_NICK             =  50,
    JOIN_CHANNEL            =  60,
    PART_CHANNEL            =  70,
    GET_USER_LIST           =  80,
    ENDOF_USER_LIST         =  90,
    GET_CHANNEL_LIST        = 100,
    ENDOF_CHANNEL_LIST      = 101,
    WHOIS                   = 102,
    ENDOF_WHOIS             = 103,
    CHANGE_CHANNEL_TOPIC    = 110,
    TOPIC_WHO               = 115,
    PRIVMSG_CHANNEL         = 120,
    PRIVMSG                 = 130,
    PROTOCOL                = 135,
    USER_COMMAND            = 140,
    MEDIA                   = 145,
    MEDIASND                = 150,
    MEDIASNDSTOP            = 160,
    MEDIAQUERY              = 170,
    MEDIAQUERYEND           = 175,
    MEDIARCV                = 180,
    MEDIARCVSTOP            = 190,
    MEDIARCVRUN             = 200,
    MEDIASET                = 210,
    MEDIASETPOS             = 215,
    MEDIASTATS              = 217,
    MEDIANOTIFY             = 220,
    MEDIARCVALL             = 230,
    MEDIARCVALLRUN          = 240,
    MEDIARESET              = 245,
    MEDIARCVALLSTOP         = 250,
    MEDIAMUTE               = 255,
    MEDIAVOICE              = 260,
    MEDIAPKTREQUEST         = 265,
    MODE                    = 270,
    MODE_USER               = 275,
    SERVER_MSG              = 280,
    SERVER_REDIR            = 285,
    KICK_USER               = 290,
    CMD_ERROR               = 300,
    OPER                    = 310,
    UDP_PING                = 319,
    UDP_PONG                = 320,
    WBOARD                  = 400,
    WBOARD_CHANNEL          = 410,
    CONTACT_ERROR           = 500,
    CONTACT_ADD             = 510,
    CONTACT_DELETE          = 520,
    CONTACT_LIST            = 530,
    CONTACT_LIST_END        = 540,
    CONTACT_ON              = 550,
    CONTACT_OFF             = 560,
    IDENTIFY_ERROR          = 600,
    IDENTIFY_REQUEST        = 610,
    IDENTIFY                = 620,
    REGISTER                = 630,
    REGISTER_ERROR          = 640,
    INVITE                  = 650,
    NOTICE                  = 660,
    APP_PING                = 670,
    MEDIAPTPINVITE          = 700,
    MEDIAPTPACK             = 710,
    MEDIAPTPREJECT          = 720,
    UNAWAY                  = 730,
    NOWAWAY                 = 740,
    APPCMD                  = 800,
    PASSWORD                = 850,
    IDLE                    = 900,
};

#endif /* __CX_CHAT_OPCODES__ */
