#ifndef GLOBAL_ERROR_H
#define GLOBAL_ERROR_H

#define RET_OK                              0
#define RET_ERROR                           1
#define RET_INVALID_ARG                     2
#define RET_LOW_MEMORY                      3
#define RET_WAIT_TIMEOUT                    4
#define RET_SOCKBUFFS_ERROR                 5
#define RET_INIT_ERROR                      6
#define RET_INVALID_MEDIA_SPEC              7
#define RET_INPUT_BUFFER_EMPTY              8
#define RET_OUTPUT_BUFFER_FULL              9
#define RET_OUTPUT_BUFFER_EMPTY             10
#define RET_MEDIA_SPEC_MISMATCH             11
#define RET_NO_FRAME_AVAILABLE              12
#define RET_INVALID_COMPRESSION_TYPE        13
#define RET_CODEC_NOT_FOUND                 14
#define RET_COULD_NOT_OPEN_CODEC            15
#define RET_KEYFRAME_NEEDED                 16
#define RET_BUFFER_TOO_SMALL                17
#define RET_DECODE_ERROR                    18
#define RET_INVALID_THREAD_TYPE             19
#define RET_EVENT_ALREADY_SET               20
#define RET_EVENT_NOT_FOUND                 21
#define RET_CREATE_THREAD_ERROR             22
#define RET_THREAD_ALREADY_CREATED          23
#define RET_THREAD_NOT_RUNNING              24
#define RET_VALID_TIMESTAMP                 25
#define RET_INVALID_TIMESTAMP               26
#define RET_VIDEO_OBJECT_INIT_ERROR         27
#define RET_AUDIO_OBJECT_INIT_ERROR         28
#define RET_NO_MEDIA_OBJECT                 29
#define RET_THREAD_ALREADY_SET              30
#define RET_CS_ALREADY_SET                  31
#define RET_CS_NOT_FOUND                    32
#define RET_COULD_NOT_ALLOC_CONTEXT         33
#define RET_COULD_NOT_ALLOC_FRAME           34
#define RET_COULD_NOT_CONVERT_PIX_FMT       35
#define RET_INPUT_BUFFER_FULL               36
#define RET_BUFFER_MEDIA_ALREADY_CREATED    37
#define RET_CLOCK_STARTED                   38
#define RET_TOO_MANY_WINDOWS                39
#define RET_WINDOW_ALREADY_CREATED          40
#define RET_NO_TIME_AVAILABLE               41
#define RET_NO_MESSAGE                      42
#define RET_BUFFER_FULL                     43
#define RET_NO_PKT_AVAILABLE                44
#define RET_DEVICE_NOT_OPENED		        45
#define RET_DEVICE_NOT_CLOSED		        46
#define RET_DEVICE_ALREADY_OPENED	        47
#define RET_INVALID_CMD	                    48
#define RET_INVALID_CAPABILITY		        49
#define RET_INVALID_CTRL                    50
#define RET_CTRL_NOT_SUPPORTED		        51
#define RET_VALUE_OUT_OF_RANGE		        52
#define RET_BUSY                            53
#define RET_DEVICE_ERROR                    54
#define RET_NOT_CAPTURING                   55
#define RET_UNSUPPORTED_PIXEL_FORMAT        56
#define RET_UNSUPPORTED_CTRL                57
#define RET_DEVICE_NOT_FOUND                58
#define RET_FILTER_AUDIO_PKT                59
#define RET_INVALID_CALL                    60
#define RET_XSERVER_CONNECTION_ERROR        61
#define RET_XSERVER_NOT_CONNECTED           62
#define RET_WINDOW_ATTR_ERROR               63
#define RET_XSERVER_CANT_GET_IMAGE          64
#define RET_STRECH_ERROR                    65
#define RET_CONVERSION_ERROR                66
#define RET_INVALID_PIXEL_FORMAT            67
#define RET_COULDNT_CREATE_CONTEXT          68
#define RET_ALREADY_INITIALIZED             69

#endif
